### ISSUE TITLE
Compitability suggestion

### ISSUE THREAD

**Issue by TheSunIsADeadlyLaser** [KxmischesDomi/HorseBanners#1]
While I understand the simplicity of GUI integration, it clashes a bit with resourcepacks, like Translucent UI of vanilla tweaks. Can't attach screenshot. don't yet understand github enough to find a way around it...
keeping the same functionality but having the item slot either invisible by configuration. or anything like that. with the ability to shift-click the banner on horse and cut it off with shears, or maybe with the very same shiftclicking. seems like a nice workaround.

or maybe light/dark mode for icons.

**Comment by TheSunIsADeadlyLaser** [comment]
https://imgur.com/a/Cb3Mf1z

**Comment by DomiIRL** [comment]
You can put [this](https://imgur.com/a/fth0gjr) image in a resourcepack under "horsebanners/textures/gui/container/horse.png" to edit the texture

**Comment by DomiIRL** [comment]
I tried using the texture of the loom inventory but I never worked with Screens before and I had enough trouble getting it to work like this

**Comment by DomiIRL** [comment]
I would really appreciate if anyone with more experience could create a pull request to fix that :)

**Comment by TheSunIsADeadlyLaser** [comment]
> You can put [this](https://imgur.com/a/fth0gjr) image in a resourcepack under "horsebanners/textures/gui/container/horse.png" to edit the texture

you. misunderstood the issue. a bit.

some photoshop wizardry later, doing what you suggested should've worked,,, but the texture remained the same. it does not look like I can alter mod's texture through resourcepack? i initially tried to simply make new one and simply load it "above" vanilla tweaks as a whole, editting the tweaks did nothing as well.

**Comment by TheSunIsADeadlyLaser** [comment]
I ended up editting the jar file of mod itself. a minor drawback. also a random horse screenie. https://imgur.com/a/sapDjMw

**Comment by DomiIRL** [comment]
So what should I change in particular to make it compatible with mods like Vanilla Tweaks?

**Comment by TheSunIsADeadlyLaser** [comment]
> So what should I change in particular to make it compatible with mods like Vanilla Tweaks?

not quite sure myself, most resourcepack modifications will require users to modify the jar files themself. Maybe including a little guidebook on how to do that will suffice, on the mod's FAQ page, or somewhere in notions. This is my first and only good idea.

Other way, which kills a charm a bit, is to make banners applieable to saddles wia crafting recipe of some kind. but it raises the question of banner retrieval or replacement. Getting rid of UI is not an option as well...

I'm all out of good ideas.

**Comment by DomiIRL** [comment]
There's a little tutorial on the curseforge page with a link to the texture and where to put it. But I think it will not be possible to fix these things for mods like Vanilla Tweaks.
